[package]
name = "elden-ring-roulette"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "xtask",
]

[dependencies]
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
